### ISSUE TITLE
[OAuth Twitter] User not saved when `auth.info.email` is nil

### ISSUE THREAD

**Issue by anubhav8421** [svs/covid19-supply-chain-backend#11]
There can be cases where the `auth` object does not contain email address because the user has disabled sharing the email( or other reason )
I have tested this with my twitter account where the `app.info.email` was coming out to be `nil`, 
so authentication worked, but no info was saved in the database
@BilalBudhani We have to ensure that if the email is not present then we have a fallback

**Comment by anubhav8421** [comment]
Turned out the api keys I was using, didnt ask permission from user to share the email, hence email was not included in the response. 
![image](https://user-images.githubusercontent.com/18699797/77775167-2f473580-7072-11ea-86ff-12f26bc1346e.png)
also the option to `ask for permission` is not clickable
 Conclusion: false negative

**Comment by BilalBudhani** [comment]
@anubhav8421 Yes, email permission has to be enabled in the Twitter app settings.

**Comment by BilalBudhani** [comment]
@anubhav8421 Can you close this issue if you've received a satisfactory response?
